### ISSUE TITLE
Add share link in "add student" menu

### ISSUE THREAD

**Issue by matthewsaxby** [sammysamau/remoteclassroom#10]
When you hit add student the first option is to invite via share link. This is currently just a static link that doesn't work. It should be the same link as the class (the URL on top of the page)

**Comment by shybovycha** [comment]
Need to fix the ability of a user to change the link. Maybe add some kind of notification when the link is copied to a clip buffer?..

**Comment by matthewsaxby** [comment]
I love both of these ideas @shybovycha. Is this something you would be able to take a look at?

**Comment by shybovycha** [comment]
Yep, I will take a look
